[langserver]
dreamchecker = true

[map_renderer]
hide_invisible = [
	"/obj/effect/landmark",
	"/turf/unsimulated/mineral",
]

[diagnostics]
var_in_proc_parameter = "error"

[debugger]
engine = "auxtools"

[code_standards]
disallow_relative_type_definitions = true
disallow_relative_proc_definitions = true
