name: Build Release

on:
  push:
    branches:
    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Clone custom items
      uses: actions/checkout@v3
      with:
        repository: Baystation12/custom-items
        path: custom-items
    - name: Build and Publish Image to Registry
      env:
        BUILD_ARGS: -Icustom-items/inc.dm
      uses: elgohr/Publish-Docker-Github-Action@93655185f260b851ede78d9a57760a8bbda65f68
      with:
        name: ${{ secrets.IMAGE_NAME }}
        username: ${{ secrets.REG_USER }}
        password: ${{ secrets.REG_PASS }}
        tags: "latest"
        buildargs: BUILD_ARGS
        registry: ${{ secrets.REG_URL }}
        cache: true
