name: Build Release

on:
  push:
    branches:
    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - name: Clone custom items
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      with:
        repository: Baystation12/custom-items
        path: custom-items
    - name: Build and Publish Image to Registry
      env:
        BUILD_ARGS: -Icustom-items/inc.dm
      uses: elgohr/Publish-Docker-Github-Action@cd13bb9a7070856a70c8fa10b7965493935de7e3
      with:
        name: ${{ secrets.IMAGE_NAME }}
        username: ${{ secrets.REG_USER }}
        password: ${{ secrets.REG_PASS }}
        tags: "latest"
        buildargs: BUILD_ARGS
        registry: ${{ secrets.REG_URL }}
        cache: true
